In [3]:
import math # import a package
import numpy as np # import a package under an alias
from sklearn import linear_model # import a submodule
from os import mkdir # import a peculiar function

In [4]:
# 1)
import string 

alphabet = string.ascii_lowercase
string1 = alphabet[2::3]
string2 = alphabet[-5::2]
string3 = alphabet[-1:-8:-2]

print(string1,string2,string3) 


cfilorux vxz zxvt


In [5]:
# 2)
(" XHEC DataScience for Business ".lower()).replace("e", "E")[1:-2]

'xhEc datasciEncE for businEs'

In [6]:
# 3)
import math    
                                                                                                                                                                  
print("{:.9f}".format(math.pi)) 

3.141592654


In [7]:
# 15)
x = np.array([1, 3, 7, 5, 15, 11, 13, 16, 17, 19])
x = np.mean(x) - x

X = np.arange(12).reshape(3,4)

print(x)
print(X)

[ 9.7  7.7  3.7  5.7 -4.3 -0.3 -2.3 -5.3 -6.3 -8.3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# 16)
mean_cols = X.mean(axis=0)
mean_cols - X

array([[ 4.,  4.,  4.,  4.],
       [ 0.,  0.,  0.,  0.],
       [-4., -4., -4., -4.]])

In [9]:
mean_rows = X.mean(axis=1)
mean_rows.reshape(3,1) - X

array([[ 1.5,  0.5, -0.5, -1.5],
       [ 1.5,  0.5, -0.5, -1.5],
       [ 1.5,  0.5, -0.5, -1.5]])

In [14]:
# 17)
np.arange(3).reshape(3,1) @ np.arange(5).reshape(1,5)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [129]:
# 18)
a = 1000
b = 1000
c = a
print(f'memory address of the variable a : {id(a)}')
print(f'memory address of the variable b : {id(b)}')
print(f'memory address of the variable c : {id(c)}')
print(f'we conclude that a and c have same address because id(c) == id(a) is {id(c) == id(a)}')

memory address of the variable a : 2063473529520
memory address of the variable b : 2063473529552
memory address of the variable c : 2063473529520
we conclude that a and c have same address because id(c) == id(a) is True


In [130]:
a += 1
print(f'we see that a == c is {a == c} and id(c) == id(a) is {id(c) == id(a)} to.')
print('we can say that variable a changes its id otherwise the variable c')

we see that a == c is False and id(c) == id(a) is False to.
we can say that variable a changes its id otherwise the variable c


In [131]:
# 19) 
A = np.array([0, 1])
B = np.array([0, 1])
C = A
print(f'memory address of the variable a : {id(A)}')
print(f'memory address of the variable b : {id(B)}')
print(f'memory address of the variable c : {id(C)}')
print(f'we conclude as the question before that a and c have same address because id(c) == id(a) is {id(c) == id(a)}')

memory address of the variable a : 2063473575472
memory address of the variable b : 2063473577680
memory address of the variable c : 2063473575472
we conclude as the question before that a and c have same address because id(c) == id(a) is False


In [132]:
A += 1
print(f'we see that a == c is {A == C} and id(c) == id(a) is {id(A) == id(C)} to')
print('we can say A and C take same memory address and same value')

we see that a == c is [ True  True] and id(c) == id(a) is True to.
we can say that variable a changes its id otherwise the variable c


In [147]:
m = 1
n = 1
print(f'when m & n equal to {m} m == n returns {m == n} and m is n returns {m is n}')
m = 1000
n = 1000
print(f'when m & n equal to {m} m == n returns {m == n} and m is n returns {m is n}')
print("for bigger numbers 'is' does not consider number with same value equal")

when m & n equal to 1 m == n returns True and m is n returns True
when m & n equal to 1000 m == n returns True and m is n returns False
for bigger numbers 'is' does not consider number with same value equal
